from aiohttp import ClientResponseError
from msgspec import DecodeError

__all__= ("ClientResponseError", "DecodeError", "PagoparError",)


class PagoparError(Exception):
    __slots__ = ("mensaje",)

    def __init__(self, mensaje: str) -> None:
        self.mensaje = mensaje


class InvalidTokenException(PagoparError):
    """
    The provided token does not match the token generated by the endpoint.
    """

class MerchantNotAuthorizedToCreateOrdersException(PagoparError):
    """
    The merchant is not authorized to create orders at this time. For security
    reasons, permissions may be temporarily restricted. Please contact the
    administrative team at administracion@pagopar.com
    """

class MerchantNotEnabledForOrderCreationException(PagoparError):
    """
    The merchant is not enabled to generate orders. This usually occurs when
    using a merchant from a non-existent environment. Please contact the
    Development team via support ticket.
    """

class MerchantNotFoundException(PagoparError):
    """
    The specified merchant does not exist. Please contact the Development team
    via support ticket.
    """

class InvalidPaymentMethodException(PagoparError):
    """
    The selected payment method is not associated with the merchant. Payment
    method restrictions may apply based on merchant category or configuration.
    If you believe this payment method should be allowed, please contact the
    Development team via support ticket.
    """

class MissingMerchantOrderIdException(PagoparError):
    """
    The merchant order ID (id_pedido_comercio) must be present in the request JSON.
    """

class DuplicateMerchantOrderIdException(PagoparError):
    """
    The merchant order ID already exists for this merchant. The field id_pedido_comercio
    must be unique across both development and production environments.
    """

class MissingDescriptionException(PagoparError):
    """
    The description field must be present, even if its value is an empty string ("").
    """

class MissingOrInvalidDocumentException(PagoparError):
    """
    The document field must be present and valid. It must contain only numeric
    characters (dots are allowed but will be removed) and have a length between
    5 and 24 characters.
    """

class MissingDocumentTypeException(PagoparError):
    """
    The document type field (tipo_documento) must be present. Currently, the
    only accepted value is "CI".
    """

class InvalidPaymentDueDateException(PagoparError):
    """
    The payment due date (fecha_maxima_pago) must be present and cannot be
    earlier than the current date.
    """

class InvalidProductDataException(PagoparError):
    """
    Invalid product data. The compras_items field must be provided.
    """

class InvalidSaleTypeException(PagoparError):
    """
    The sale type field must be defined. Allowed values are VENTA-COMERCIO
    and COMERCIO-HEREDADO.
    """

class MissingBuyerEmailException(PagoparError):
    """
    Buyer information must be provided. The comprador field is required.
    """

class InvalidAmountException(PagoparError):
    """
    The total amount must be between Gs. 1,000 and Gs. 50,000,000.
    """

class InvalidCurrencyException(PagoparError):
    """
    The currency field must exist. Currently, the only supported currency is PYG.
    """

class ItemMinimumPriceException(PagoparError):
    """
    Each item in compras_items must have a minimum price of Gs. 1,000.
    """

_errors = {
    "Token no coincide": InvalidTokenException,
    "El comercio no tiene permiso para crear pedidos": MerchantNotAuthorizedToCreateOrdersException,
    "Comercio no habilitado para generar pedidos": MerchantNotEnabledForOrderCreationException,
    "Comercio no existe": MerchantNotFoundException,
    "Forma de pago seleccionado no corresponde": InvalidPaymentMethodException,
    "El id pedido del comercio debe de estar presente": MissingMerchantOrderIdException,
    "El pedido ya existe para ese comercio": DuplicateMerchantOrderIdException,
    "La descripcion debe de estar presente": MissingDescriptionException,
    "El documento debe de estar presente": MissingOrInvalidDocumentException,
    "El tipo documento debe de estar presente": MissingDocumentTypeException,
    "Fecha inválida.": InvalidPaymentDueDateException,
    "Datos de productos invalidos": InvalidProductDataException,
    "venta invalido": InvalidSaleTypeException,
    "El email del comprador debe existir": MissingBuyerEmailException,
    "Monto debe ser mínimo Gs. 1.000 o máximo de Gs. 50.000.00": InvalidAmountException,
    "La moneda no existe": InvalidCurrencyException,
    "El precio mínimo de cada item debe ser de Gs. 1.000": ItemMinimumPriceException
}

def parse_error(message: str) -> PagoparError: 
    error_cls = _errors.get(message, PagoparError)
    return error_cls(message)
